version: '3.7'

services:
  db:
    build: &default-build
      context: ./db
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./db/postgresql.conf:/etc/postgresql.conf
    environment:
      - PGTZ=Asia/Tokyo
    ports:
      - "${DB_PORT}:5432"

  app: &default-app
    build : 
      <<: *default-build
      context: ./app
    environment:
      - TZ=Asia/Tokyo
      - FLASK_DEBUG=1
      - PYTHON_ENV=development
    volumes: 
      - ./app:/srv
      - ./store:/store
    depends_on:
      - migration

  client:
    build : 
      <<: *default-build
      context: ./app
    volumes: 
      - ./client:/srv
    depends_on:
      - api

  api:
    command:  sh start_api.sh
    <<: *default-app
    depends_on:
      - db
      - migration

  migration:
    build:
      <<: *default-build
      context: ./migration
    volumes:
      - ./migration:/srv
    depends_on:
      - db

  board: &default-node
    build:
      <<: *default-build
      target: dev
      context: ./board
    environment: 
      - NODE_ENV=development
      - http_proxy
      - https_proxy
    volumes:
      - ./board:/srv
    command: npm run watch

  storybook:
    <<: *default-node
    command: npm run storybook
    ports:
      - "${STORYBOOK_PORT}:9001"

  web:
    build:
      <<: *default-build
      context: ./web
    volumes:
      - ./web/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./board/dist:/public/
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
      - board

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
