version: '3.7'

services:
  db:
    image: "h4nyu/mlboard_db:${TAG}"

  api: &default-app
    image: "h4nyu/mlboard_app:${TAG}"
    command: cargo run --release
    depends_on:
      - db
      - migration

  migration:
    image: "h4nyu/mlboard_migration:${TAG}"
    depends_on:
      - db

  board: &default-node
    image: "h4nyu/mlboard_board:${TAG}"
    command: yarn watch

  web:
    image: "h4nyu/mlboard_web:${TAG}"
    volumes:
      - ./web/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./board/dist:/public/
    depends_on:
      - api
      - board

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
