version: '2.4'

services:
  db:
    ports:
      - "5432:5432"

  api:
    volumes:
      - ./app:/srv
    environment: &python-env
      - PYTHON_ENV=development

  migration:
    volumes:
      - ./migration:/srv

  board: &node-env
    environment: 
      - NODE_ENV=development
      - http_proxy
      - https_proxy
    build:
      target: dev
    volumes:
      - ./board:/srv
    command: npm start

  storybook:
    <<: *node-env
    command: npm run storybook
    ports:
      - "9001:9001"

  web:
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./board/dist:/public/
    ports:
      - "80:80"
