version: '2.4'

services:
  db:
    build: 
      context: ./db
      args: &build-args
        - http_proxy
        - https_proxy

  api:
    build: 
      context: ./app
      args: *build-args
    command: gunicorn --bind 0.0.0.0:5000 mlboard:api
    depends_on:
      - db

  migration:
    build: 
      context: ./migration
      args: *build-args
    depends_on:
      - db

  board:
    build: 
      context: ./board
      args: *build-args

  storybook:
    build: 
      context: ./board
      args: *build-args

  web:
    build: 
      context: ./web
      args: *build-args
    depends_on:
      - api
      - board
