version: '3.7'

services:
  db:
    image: "h4nyu/mlboard_db:${TAG}"
    ports:
      - "${DB_PORT}:5432"

  api: &default-app
    image: "h4nyu/mlboard_app:${TAG}"
    volumes: 
      - ./app:/srv
      - ./store:/store
    depends_on:
      - db
      - migration

  migration:
    volumes:
      - ./migration:/srv
    image: "h4nyu/mlboard_migration:${TAG}"
    depends_on:
      - db

  board: &default-node
    image: "h4nyu/mlboard_board:${TAG}"
    volumes:
      - ./board:/srv
    command: yarn watch

  web:
    image: "h4nyu/mlboard_web:${TAG}"
    volumes:
      - ./web/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./board/dist:/public/
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
      - board

  storybook:
    image: "h4nyu/mlboard_board:${TAG}"
    volumes:
      - ./board:/srv
    command: yarn storybook

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
