version: '3.7'

services:
  db:
    build: &default-build
      context: ./db
      args:
        - http_proxy
        - https_proxy

  app:
    build : 
      <<: *default-build
      context: ./app
      target: ${STAGE}

  migration:
    build:
      <<: *default-build
      context: ./migration

  ui:
    build:
      <<: *default-build
      context: ./ui
      target: ${STAGE}
