version: '3.7'

services:
  db:
    image: h4nyu/mlboard_db
    ports:
      - "${DB_PORT}:5432"

  api: &default-app
    image: h4nyu/mlboard_app
    command: sh start_api.sh
    volumes: 
      - ./app:/srv
      - ./store:/store
    depends_on:
      - db
      - migration

  migration:
    volumes:
      - ./migration:/srv
    image: h4nyu/mlboard_migration
    depends_on:
      - db

  board: &default-node
    image:  h4nyu/mlboard_board
    volumes:
      - ./board:/srv
    command: yarn watch

  web:
    image:  h4nyu/mlboard_web
    volumes:
      - ./web/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./board/dist:/public/
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
      - board

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
