version: '3.4'

services:
  db:
    build: 
      context: ./db
      args:
        - http_proxy
        - https_proxy
    restart: on-failure

  api:
    build: 
      context: ./api
      args:
        - http_proxy
        - https_proxy
    command: flask run --host=0.0.0.0
    restart: on-failure
    depends_on:
      - db

  migration:
    build: 
      context: ./migration
      args:
        - http_proxy
        - https_proxy
    restart: on-failure
    depends_on:
      - db

  board:
    build: 
      context: ./board
      target: dev
      args:
        - http_proxy
        - https_proxy
    restart: on-failure

  web:
    build: 
      context: ./web
      args:
        - http_proxy
        - https_proxy
    depends_on:
      - api
      - board
    restart: on-failure
