version: '3.7'

services:
  api:
    volumes: 
      - ./app:/srv
    security_opt:
      - seccomp:unconfined
    ports:
      - "${DB_PORT}:5432"

  migration:
    volumes:
      - ./migration:/srv

  board: &default-node
    volumes:
      - ./board:/srv

  web:
    volumes:
      - ./web/nginx.prod.conf:/etc/nginx/nginx.conf

    ports:
      - "${WEB_PORT}:80"

  storybook:
    image: "h4nyu/mlboard_board:${TAG}"
    volumes:
      - ./board:/srv
    command: yarn storybook
    ports:
      - "${STORYBOOK_PORT}:9001"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

