version: '3.4'

services:
  db:
    ports:
      - "5432:5432"
  api:
    volumes:
      - ./api:/srv
    environment:
      - FLASK_DEBUG=1
      - PYTHON_ENV=development

  migration:
    volumes:
      - ./migration:/srv

  board:
    environment:
      - NODE_ENV=development
      - http_proxy
      - https_proxy
    volumes:
      - ./board:/srv
    command: npm start

  web:
    volumes:
      - ./web/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./board/dist:/public/
    ports:
      - "80:80"
