version: '3.7'

services:
  db:
    image: h4nyu/mlboard_db
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app: &default-app
    image: h4nyu/mlboard_app
    volumes:
      - ./web-data:/public
    depends_on:
      - migration
    ports:
      - "${WEB_PORT}:5000"

  migration:
    image: h4nyu/mlboard_migration
    depends_on:
      - db

  board: &default-node
    image:  h4nyu/mlboard_ui
    volumes:
      - ./web-data:/public

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
