version: '3.7'

services:
  api:
    volumes: 
      - ./app:/srv
    ports:
      - "${DB_PORT}:5432"

  board: &default-node
    volumes:
      - ./board:/srv

  db:
    volumes:
      - ./db:/srv
      - ./db/upgrade.sh:/docker-entrypoint-initdb.d/upgrade.sh

  web:
    volumes:
      - ./web/nginx.prod.conf:/etc/nginx/nginx.conf

    ports:
      - "${WEB_PORT}:80"

  storybook:
    image: "h4nyu/mlboard_board:${TAG}"
    volumes:
      - ./board:/srv
    command: yarn storybook
    ports:
      - "${STORYBOOK_PORT}:9001"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

