version: '3.7'

services:
  db:
    image: "h4nyu/mlboard_db:${TAG}"
    build: &default-build
      context: ./db
      args:
        - http_proxy
        - https_proxy
    ports:
      - "${DB_PORT}:5432"

  api: &default-app
    command: sh start_api.sh
    image: "h4nyu/mlboard_app:${TAG}"
    build : 
      <<: *default-build
      context: ./app
    depends_on:
      - db
      - migration

  migration:
    command: alembic upgrade head
    volumes:
      - ./migration:/srv
    image: "h4nyu/mlboard_migration:${TAG}"
    build:
      <<: *default-build
      context: ./migration
    depends_on:
      - db

  board: &default-node
    image: "h4nyu/mlboard_board:${TAG}"
    build:
      <<: *default-build
      context: ./board
    volumes:
      - ./web-data:/srv/dist

  web:
    image: "h4nyu/mlboard_web:${TAG}"
    build:
      <<: *default-build
      context: ./web
    volumes:
      - ./web-data:/public
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
      - board

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
