version: '3.4'
volumes: 
  db_data:
  board_data:

services:
  db:
    image: h4nyu/mlboard_db
    volumes:
      - db_data:/var/lib/postgresql/data
    logging: &default-log
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      restart_policy:
          condition: on-failure
      mode: global

  api:
    image: h4nyu/mlboard_api
    depends_on:
      - db
    logging: *default-log
    deploy:
      restart_policy:
          condition: on-failure
      mode: replicated
      replicas: 4


  migration:
    image: h4nyu/mlboard_migration
    depends_on:
      - db
    logging: *default-log
    deploy:
      restart_policy:
          condition: none
      mode: replicated
      replicas: 1


  board:
    image: h4nyu/mlboard_board
    volumes:
      - board_data:/public
    logging: *default-log
    deploy:
      restart_policy:
          condition: none
      mode: replicated
      replicas: 1

  web:
    image: h4nyu/mlboard_web
    volumes:
        - board_data:/public
    depends_on:
      - api
      - board
    logging: *default-log
    ports:
      - "80:80"
    deploy:
      restart_policy:
          condition: on-failure
      mode: replicated
      replicas: 1
