version: '3'

services:
  db:
    image: h4nyu/mlboard_db
    logging: &default-logging
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    
    restart: on-failure

  api: &default-app
    image: h4nyu/mlboard_app
    command:  python api.py
    restart: on-failure
    logging: *default-logging
    depends_on:
      - db

  migration:
    image: h4nyu/mlboard_migration
    logging: *default-logging
    depends_on:
      - db

  board:
    image: h4nyu/mlboard_board
    volumes:
      - ./web-data:/public
    logging: *default-logging

  web:
    image: h4nyu/mlboard_web
    volumes:
        - ./web-data:/public
    depends_on:
      - api
      - board
    logging: *default-logging
    restart: on-failure
    ports:
      - "${WEB_PORT}:80"
