version: '3.7'

services:
  db:
    image: h4nyu/mlboard_db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  api: &default-app
    image: h4nyu/mlboard_app
    depends_on:
      - db

  board: &default-node
    image:  h4nyu/mlboard_board
    volumes:
      - ./web-data:/public

  web:
    image:  h4nyu/mlboard_web
    volumes:
      - ./web-data:/public
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
      - board

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
