version: '3'

services:
  db:
    build: &default-build
      context: ./db
      args:
        - http_proxy
        - https_proxy
    image: h4nyu/mlboard_db

  app: &default-app
    build : 
      <<: *default-build
      context: ./app
    image: h4nyu/mlboard_app

  migration:
    build:
      <<: *default-build
      context: ./migration
    image: h4nyu/mlboard_migration

  board: &default-node
    build:
      <<: *default-build
      context: ./board
    image:  h4nyu/mlboard_board

  web:
    build:
      <<: *default-build
      context: ./web
    image:  h4nyu/mlboard_web
