version: '2.4'

services:
  db:
    build: &default-build
      context: ./db
      args: 
        - http_proxy
        - https_proxy
    ports:
      - "${DB_PORT}:5432"
  app: &default-app 
    build: 
      <<: *default-build
      context: ./app
    command: uvicorn mlboard:webapi_app --reload --host 0.0.0.0 --port 5000 
    volumes:
      - ./app:/srv
    environment: &python-env
      - PYTHON_ENV=development

  api:
    <<: *default-app
    command: uvicorn mlboard:webapi_app --reload --host 0.0.0.0 --port 5000 
    depends_on:
      - db

  migration:
    build: 
      <<: *default-build
      context: ./migration
    volumes:
      - ./migration:/srv
    depends_on:
      - db

  board: &node-env
    build: 
      <<: *default-build
      context: ./board
      target: dev

    environment: 
      - NODE_ENV=development
      - http_proxy
      - https_proxy
    volumes:
      - ./board:/srv
    command: npm run watch


  storybook:
    <<: *node-env
    command: npm run storybook
    ports:
      - "${STORYBOOK_PORT}:9001"

  web:
    build: 
      <<: *default-build
      context: ./web
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./board/dist:/public/
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
      - board
