version: '3.7'

services:
  db:
    image: "h4nyu/mlboard_db:${TAG}"

  api: &default-app
    image: "h4nyu/mlboard_app:${TAG}"
    depends_on:
      - migration

  migration:
    image: "h4nyu/mlboard_migration:${TAG}"
    depends_on:
      - db

  board: &default-node
    image: "h4nyu/mlboard_board:${TAG}"
    command: yarn watch

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
