version: '3.7'

services:
  db:
    build: &default-build
      context: ./db
      args:
        - http_proxy
        - https_proxy
    image: "h4nyu/mlboard_db:${TAG}"
  app:
    build : 
      <<: *default-build
      context: ./app
    image: "h4nyu/mlboard_app:${TAG}"

  app_go:
    build : 
      <<: *default-build
      context: ./app_go
    image: "h4nyu/mlboard_app_go:${TAG}"

  migration:
    build:
      <<: *default-build
      context: ./migration
    image: "h4nyu/mlboard_migration:${TAG}"

  board:
    build:
      <<: *default-build
      context: ./board
      target: ${STAGE}
    image: "h4nyu/mlboard_board:${TAG}"

  web:
    build:
      <<: *default-build
      context: ./web
    image: "h4nyu/mlboard_web:${TAG}"
