from enum import Enum


class StatusLevel(int, Enum):
    CRITICAL = 50
    ERROR = 40
    HARD_WARNING = 35
    WARNING = 30
    INFO = 20
    NOTSET = 0


class LogTypes(str, Enum):
    TOKKI_EVENT_LOG = "TOKKI_EVENT_LOG"
    TOKKI_PROCESS_LOG = "TOKKI_PROCESS_LOG"
    TOKKI_SENSOR_LOG = "TOKKI_SENSOR_LOG"


class TaskTypes(str, Enum):
    ETL_TOKKI_SENSOR_LOG = "ETL_TOKKI_SENSOR_LOG"
    ETL_TOKKI_STATE_SECTION_LOG = "ETL_TOKKI_STATE_SECTION_LOG"
    ETL_TOKKI_STATE_SECTION_SPAN = "ETL_TOKKI_STATE_SECTION_SPAN"
    ETL_TOKKI_EVENT_SECTION_LOG = "ETL_TOKKI_EVENT_SECTION_LOG"
